# Generated by Django 3.2.4 on 2021-07-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='conent',
            new_name='content',
        ),
    ]
